# Generated by Django 2.1.15 on 2020-06-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0121_auto_20200213_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaldata',
            name='metadata',
        ),
    ]
