# Generated by Django 2.1.15 on 2020-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0122_remove_clinical_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='context',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='patient_review_item',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='registry',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('R', 'Caregiver Review')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='item_type',
            field=models.CharField(choices=[('CF', 'Consent Item'), ('DF', 'Demographics Field'), ('CA', 'Clinician Access'), ('MT', 'Multi Target'), ('SC', 'Section Monitor'), ('MI', 'Add to Section'), ('MU', 'Update Section')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
