# Generated by Django 2.1.15 on 2020-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0123_remove_verifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondataelement',
            name='abnormality_condition',
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=10, null=True),
        ),
    ]
