# Generated by Django 2.1.15 on 2020-06-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0124_remove_abnormality_and_minmax_from_cdes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaction',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='customaction',
            name='registry',
        ),
        migrations.DeleteModel(
            name='CustomAction',
        ),
    ]
