version: '2'
services:

  # data only container pattern
  datadev:
    extends:
      file: docker-compose-common.yml
      service: datadev

  db:
    extends:
      file: docker-compose-common.yml
      service: db

  cache:
    extends:
      file: docker-compose-common.yml
      service: cache

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx
    depends_on:
      - uwsgi

  runserver:
    extends:
      file: docker-compose-common.yml
      service: runserver
    command: grdr
    volumes_from:
      - datadev
    depends_on:
      - db
      - cache
    ports:
      - "8000:8000"

  uwsgi:
    extends:
      file: docker-compose-common.yml
      service: uwsgi
    volumes_from:
      - datadev
    depends_on:
      - db
      - cache
      - runserver
